.TH vaulted\-upgrade 1
.SH NAME
.PP
vaulted upgrade \- upgrades legacy vaults to the current vault format
.SH SYNOPSIS
.PP
\fB\fCvaulted upgrade\fR
.SH DESCRIPTION
.PP
Reads legacy vaults and converts them to the current vault format. The same
password is used for the converted vaults.
.PP
The exit code is equal to the number of vaults that could not be upgraded.
