.TH vaulted\-shell 1
.SH NAME
.PP
vaulted shell \- starts an interactive shell with the secrets for the vault loaded into the shell
.SH SYNOPSIS
.PP
\fB\fCvaulted shell\fR \fIname\fP
.SH DESCRIPTION
.PP
Starts an interactive shell (uses the \fB\fCSHELL\fR environment variable, if set;
otherwise defaults to \fB\fC/bin/sh\fR).
