.TH vaulted\-edit 1
.SH NAME
.PP
vaulted edit \- interactively edits the content of an existing vault
.SH SYNOPSIS
.PP
\fB\fCvaulted edit\fR \fIname\fP
.SH DESCRIPTION
.PP
Spawns an interactve mode for editing the content of an existing vault.
.PP
Upon quitting, the new content is saved to the vault.
