.TH vaulted\-exec 1
.SH NAME
.PP
vaulted exec \- executes shell commands with a given vault or role
.SH SYNOPSIS
.PP
\fB\fCvaulted exec\fR [\fIOPTIONS\fP] \fIname\fP \fIcommands\fP
.br
\fB\fCvaulted exec\fR [\fIOPTIONS\fP] \fIname\fP \fB\fC\-\-\fR \fIcommands\fP
.br
\fB\fCvaulted exec\fR [\fIOPTIONS\fP] \fB\fC\-\-assume\fR \fIarn\fP \fB\fC\-\-\fR \fIcommands\fP
.SH DESCRIPTION
.PP
Executes shell commands with a given vault or role. Exec combines the features
from \fB\fCvaulted shell\fR with the command execution of \fB\fCvaulted \-n\fR\&.
.SH OPTIONS
.TP
\fB\fC\-\-assume\fR \fIarn\fP
Specifies the full ARN or the role name of the role to assume. See
\fBASSUMING A ROLE\fP below for details on how Vaulted assumes roles.
.IP
Role assumption may be performed without specifying a vault to spawn from.
When invoked this way, credentials are sourced from default locations (e.g.
environment, configuration files, instance profile, etc.).
.TP
\fB\fC\-\-no\-session\fR
Disables the generation of temporary credentials and role assumption. The
permanent credentials stored in the vault are used instead.
.IP
Role assumption can be performed after spawning a shell using the \fB\fC\-\-assume\fR
command with the ARN of the role you wish to assume.
.TP
\fB\fC\-\-refresh\fR
Start a new session with new temporary credentials and a refreshed expiration.
.TP
\fB\fC\-\-ssh\-generate\-key\fR
Generate and load an RSA key into the spawned session's SSH agent.
.TP
\fB\fC\-\-ssh\-proxy\-agent\fR
Exposes the external SSH agent to the spawned session.
.TP
\fB\fC\-\-ssh\-signing\-url\fR
Configures the endpoint to use for SSH key signing. Currently only configured
to work with HashiCorp Vault endpoints.
.TP
\fB\fC\-\-ssh\-signing\-users\fR
Configures the users to sign SSH keys for when key signing is enabled.
.SH AWS KEY
.PP
[comment]: # (WHEN MODIFYING THESE DOCS, ALSO UPDATE: vaulted\-env.1.md and
vaulted\-shell.1.md)
.PP
Vaulted uses permanent credentials stored in the vault to generate temporary
credentials using AWS STS. The resulting credentials are configured to last for
the duration of the vault session (configured via \fB\fCvaulted edit\fR).
.PP
Temporary credentials must be used in order to assume a role.
.PP
\fINote:\fP because Vaulted defaults to substituting permanent credentials with
temporary credentials, the credentials you provide to Vaulted may not match
those in a spawned session.
.PP
Vaulted uses AWS standard environment variables for credentials:
.RS
.IP \(bu 2
\fB\fCAWS_ACCESS_KEY_ID\fR
.br
An identifier for the access key. Unique to each set of permanent or
temporary credentials.
.IP \(bu 2
\fB\fCAWS_SECRET_ACCESS_KEY\fR
.br
The secret used to sign requests. Unique to each set of permanent or
temporary credentials.
.IP \(bu 2
\fB\fCAWS_SESSION_TOKEN\fR / \fB\fCAWS_SECURITY_TOKEN\fR
.br
Provided when using temporary credentials. \fB\fCAWS_SECURITY_TOKEN\fR is provided
to support legacy SDKs.
.RE
.SH ASSUMING A ROLE
.PP
[comment]: # (WHEN MODIFYING THESE DOCS, ALSO UPDATE: vaulted\-env.1.md and
vaulted\-shell.1.md)
.PP
A role to assume can be specified either in a vault's configuration (via
\fB\fCvaulted edit\fR) or specified via the \fB\fC\-\-assume\fR option.
.PP
Vaulted first generates and caches a session for the vault (assuming a vault
\fIname\fP was specified) and uses the resulting session to perform the assume role
call. This allows the session to be cached for a longer duration than the assume
roll call will allow (maximum of 1 hour). This also means that the assume role
call is performed each time a new environment is spawned from the session.
.PP
You can also specify a role name and Vaulted will attempt
to create the full ARN from it, like so:
.PP
.RS
.nf
vaulted exec \-\-assume SuperRole \-\- command
.fi
.RE
.PP
which would resolve to the full arn \fB\fCarn:aws:iam::111222333444:role/SuperRole\fR\&.
.PP
When assuming a role, the maximum duration of the resulting credentials is 1
hour, regardless of the duration specified in the vault's configuration.
.PP
In addition to the variables specified above, Vaulted provides additional
environment variables with information about the role:
.RS
.IP \(bu 2
\fB\fCVAULTED_ENV_ROLE_ACCOUNT_ID\fR
.br
The account ID of the role assumed.
.IP \(bu 2
\fB\fCVAULTED_ENV_ROLE_ARN\fR
.br
The full ARN of the role assumed.
.IP \(bu 2
\fB\fCVAULTED_ENV_ROLE_NAME\fR
.br
The name of the role assumed.
.IP \(bu 2
\fB\fCVAULTED_ENV_ROLE_PARTITION\fR
.br
The AWS partition of the role assumed.
.IP \(bu 2
\fB\fCVAULTED_ENV_ROLE_PATH\fR
.br
The path of the role assumed.
.RE
.PP
For example:
.PP
.RS
.nf
vaulted exec \-\-assume arn:aws:iam::111222333444:role/path/SuperRole \-\- command
.fi
.RE
.PP
would result in the following variables being set:
.PP
.RS
.nf
VAULTED_ENV_ROLE_ACCOUNT_ID=111222333444
VAULTED_ENV_ROLE_ARN=arn:aws:iam::111222333444:role/path/SuperRole
VAULTED_ENV_ROLE_NAME=SuperRole
VAULTED_ENV_ROLE_PARTITION=aws
VAULTED_ENV_ROLE_PATH=/path/
.fi
.RE
.SH GUI Password Prompts
.PP
GUI\-based password prompts can be used by setting the \fB\fCVAULTED_ASKPASS\fR
variable. See \fB\fCvaulted(1)\fR for more details.
