.TH vaulted\-edit 1
.SH NAME
.PP
vaulted edit \- interactively edits the content of an existing vault
.SH SYNOPSIS
.PP
\fB\fCvaulted edit\fR \fIname\fP
.SH DESCRIPTION
.PP
Spawns an interactve mode for editing the content of an existing vault.
.PP
Upon quitting, the new content is saved to the vault.
.SH AWS KEY
.RS
.IP \(bu 2
k \- Key
.br
Manages Access Key ID and Secret Access Key credentials.
.IP \(bu 2
m \- MFA
.br
Manages MFA (multi\-factor authentication) ARN or serial number. If enabled,
user will be prompted to enter MFA code when accessing vault. MFA will
remain active for the vault duration.
.RE
.PP
   If you are using STS credentials, which occurs by default (see the 't'
   option below for details), you must have MFA enabled to invoke any IAM calls.
* r \- Role
.br
   ARN of role to be assumed when accessing vault.
   When assuming a role, the maximum duration allowed by AWS is 1 hour. If your
   duration is greater than 1 hour when setting a role, the duration will be
   adjusted to 1 hour.
* t \- Substitute with temporary credentials
.br
   Toggles whether your AWS credentials are substituted with a set of temporary
   credentials. For more details on this process, see the documentation for
   \fB\fCvaulted shell\fR\&.
* S \- Show/Hide Key
.br
   Toggles whether Secret Access Key ID is displayed when viewing vault
   details in the edit menu. This setting only affects the current editing
   session and is reset to hidden each time the vault is reopened for editing.
* D \- Delete
.br
   Removes all AWS details stored in the vault.
