.TH vaulted\-rm 1
.SH NAME
.PP
vaulted rm \- removes existing vaults
.SH SYNOPSIS
.PP
\fB\fCvaulted rm\fR \fIname\fP \fI\&...\fP
.PP
\fB\fCvaulted delete\fR \fIname\fP \fI\&...\fP
.br
\fB\fCvaulted remove\fR \fIname\fP \fI\&...\fP
.SH DESCRIPTION
.PP
Removes the vaults specified by \fIname\fP\&. The exit code is equal to the number of
vaults that could not be removed.
.PP
If a vault cannot be removed, the error is displayed on stdout.
