.TH vaulted\-add 1
.SH NAME
.PP
vaulted add \- interactively creates the content of a new vault
.SH SYNOPSIS
.PP
\fB\fCvaulted add\fR \fIname\fP
.PP
\fB\fCvaulted create\fR \fIname\fP
.br
\fB\fCvaulted new\fR \fIname\fP
.SH DESCRIPTION
.PP
Spawns an interactve mode for editing the content of a new vault.
.PP
Upon quitting, the new content is saved to the vault.
